name: CI/CD Pipeline reloader

on:
  push:
    branches:
      - main

jobs:
  dockerize-reloader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change to workdir
        working-directory: ./reloader
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-reloader:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-reloader:latest